// CONFIG
// Tuning values live here so the prototype can grow without burying numbers.

window.OceanConfig = {
  GRID: {
    cols: 20,
    rows: 13,
  },

  TERRAIN: {
    enabled: false,
    baseWorldSpeed: 0.00012,
    boostMultiplier: 1.55,
    slowMultiplier: 0.64,
    speedEase: 0.08,
    sampleDepth: 0.62,
    // Terrain art waits until about the 3rd grid row from the horizon before drawing.
    nearHorizonDepth: 0.17,
    // Fade terrain out across the last rows before the surfboard rail.
    foregroundFadeRows: 2,
    patches: [],
  },

  OBSTACLES: {
    enabled: true,
    // Markers attach to cell centers.
    // cellCol is 0..GRID.cols - 2. cellRow is 0..GRID.rows - 2.
    centerAnchor: "cell-center",
    placementRules: {
      minVertexDistance: 4,
      distanceMode: "manhattan",
      warnOnly: true,
    },
    classes: [
      {
        type: "seaweed",
        name: "Seaweed",
        visual: {
          color: "#00FF1D",
          tileSpan: { cols: 2, rows: 2 },
          vertexFootprint: { cols: 3, rows: 3, total: 9 },
          markerShape: "checkerboard",
        },
        terrainEffect: { kind: "speed-multiplier", value: 0.33 },
        timing: { enabled: false },
        collision: { enabled: true, effect: "slow" },
        functionNote: "Slows current world speed to one third.",
      },
      {
        type: "tide",
        name: "Tide",
        visual: {
          color: "#FF5AEA",
          tileSpan: { cols: 2, rows: 3 },
          vertexFootprint: { cols: 3, rows: 4, total: 12 },
          markerShape: "tide-band",
        },
        terrainEffect: { kind: "speed-multiplier", value: 1.5 },
        timing: { enabled: false },
        collision: { enabled: true, effect: "speed-up" },
        functionNote: "Increases current world speed by 50%.",
      },
      {
        type: "jumpwave",
        name: "Jumpwave",
        visual: {
          color: "#D4C800",
          tileSpan: { cols: 1, rows: 4 },
          vertexFootprint: { cols: 2, rows: 5, total: 10 },
          markerShape: "vertical-wave",
        },
        terrainEffect: { kind: "timed-speed-multiplier", value: 3, duration: 900 },
        timing: { enabled: true, input: "Space", rowWindow: 1, laneWindow: 0.55 },
        collision: { enabled: true, effect: "jump-shift" },
        jumpEffect: {
          maxColumnHop: 4,
          liftPixels: 46,
          liftDuration: 120,
          hangDuration: 160,
          landDuration: 260,
          bouncePixels: 8,
          railCue: {
            enabled: true,
            baseRadius: 8,
            expandRadius: 6,
            pulseSpeed: 0.012,
            reactionTimeMs: 700,
            minDepthWindow: 0.035,
          },
        },
        functionNote: "Increases speed by 200% and later moves the player over four columns.",
      },
    ],
    placements: [
      { id: "seaweed-a", type: "seaweed", cellCol: 3, cellRow: 7 },
      { id: "tide-a", type: "tide", cellCol: 9, cellRow: 5 },
      { id: "jumpwave-a", type: "jumpwave", cellCol: 15, cellRow: 4 },
    ],
  },

  OBSTACLE_GENERATOR: {
    enabled: true,
    requireAudio: false,
    spawnIntervalMs: 720,
    spawnJitterMs: 360,
    maxGeneratedObstacles: 5,
    generatedLifetimeMs: 9500,
    spawnRows: [0, 1, 2],
    lanePadding: 1,
    minRowGap: 3,
    minColGap: 2,
    minSameTypeRowGap: 3,
    minJumpwaveGapMs: 2100,
    maxAttemptsPerSpawn: 9,
    safeLaneRequired: true,
    safeLaneCount: 2,
    safeLaneRowWindow: 3,
    baseSpawnChance: 0.18,
    audioInfluence: 0.72,
    quietSeaweedBias: 0.18,
    bassJumpwaveBias: 0.52,
    trebleTideBias: 0.5,
    volumeDensityBias: 0.34,
    hitBonus: 0.28,
  },

  TIMING: {
    enabled: false,
    targetLaneRadius: 0.5,
    targetDepthSize: 0.075,
    hitWindowDepth: 0.045,
    laneWindow: 0.48,
    perfectBoostMultiplier: 3.1,
    boostDuration: 1100,
    cooldownDuration: 900,
    respawnDelay: 550,
  },

  AUDIO: {
    enabled: true,
    // Keep filenames and real container formats matched for GitHub Pages MIME handling.
    sources: [
      "./assets/audio/test.ogg",
      "./assets/audio/test.mp3",
      "./assets/audio/test.m4a",
      "./assets/audio/test.wav",
    ],
    mobileSources: [
      "./assets/audio/test.mp3",
      "./assets/audio/test.m4a",
      "./assets/audio/test.wav",
    ],
    safariSources: [
      "./assets/audio/test.mp3",
      "./assets/audio/test.m4a",
      "./assets/audio/test.wav",
    ],
    contextResumeTimeout: 1200,
    sourceStartTimeout: 2200,
    playbackAdvanceTimeout: 1400,
    playbackStallTimeout: 2400,
    delayedAutoStart: false,
    autoStartDelay: 1600,
    fftSize: 1024,
    smoothingTimeConstant: 0.68,
    gridBaseWaveAmount: 0.06,
    gridBaseRippleAmount: 0.018,
    bassWaveAmount: 0.42,
    trebleShimmerAmount: 0.12,
    volumeGlowAmount: 0.18,
    gridBassLiftAmount: 0.34,
    gridTrebleRippleAmount: 0.16,
    gridVolumeLiftAmount: 0.08,
    gridHitLiftAmount: 0.26,
    gridPulseGlowAmount: 16,
    gridPulseWidthAmount: 1.4,
    whiteThresholdShift: 0.12,
    terrainGlowAmount: 20,
    terrainWidthAmount: 2.2,
    showDebugReadout: true,
  },

  PERFORMANCE: {
    enableCanvasShadows: false,
    enableAudioGlow: false,
    enableMobileStrokeReduction: false,
    maxPixelRatioDesktop: 1,
    maxPixelRatioSmall: 1,
    mobileModeSmallSide: 900,
    mobileModeFrameMs: 24,
    fullModeRecoverFrameMs: 17,
    mobileGridRowStride: 2,
    mobileGridColumnStride: 2,
    mobileDecorRingStride: 2,
    mobileDecorSpokeStride: 2,
    mobileDecorStepScale: 0.55,
    targetFrameMs: 18,
    slowFrameMs: 28,
    glowRecoverRate: 0.018,
    glowDropRate: 0.08,
    minGlowScale: 0.08,
    showFrameRate: true,
  },

  VIEW: {
    horizonY: 0.24,
    frontY: 0.9,
    backHalfWidth: 0.08,
    frontHalfWidth: 0.62,
    waveLift: 130,
  },

  DECOR: {
    rings: 6,
    spokes: 7,
    pulseSpeed: 0.0012,
    twistSpeed: 0.00045,
  },

  PLAYER: {
    startingLane: 10,
    minLane: 1,
    maxLane: 18,
    laneMoveDuration: 38,
    holdInitialDelay: 70,
    holdPulseInterval: 45,
    laneEase: "easeOut",
    allowLaneRetarget: true,
    tiltMaxDegrees: 12,
    tiltResponse: 0.35,
    tiltReturnSpeed: 0.18,
    halfWidth: 20,
    length: 120,
    artReferenceLaneSpacing: 78,
    artMinScale: 0.26,
    artMaxScale: 1,
    artPhoneScaleBoost: 1.08,
    artTabletScaleBoost: 1,
    railAngleFollow: 0.78,
    railRowsFromFront: 3,
    showLaneTicks: true,
    laneDotBaseRadius: 2,
    laneDotActiveRadius: 3.4,
    laneDotPulseAmount: 2.4,
    laneDotPulseSpeed: 0.006,
    laneDotMaxRadius: 10,
  },
};
